#' Compute SPAROscores from pre-computed gene ranks
#'
#' Computes SPAROscores for one or more gene signatures using the rank matrix
#' and rank caps generated by \code{\link{get_sparoranks}}.
#'
#' SPAROscores quantify signature activity based on the normalized Spearman
#' footrule distance between observed signature gene ranks and a column-specific
#' rank cap. Higher scores indicate that signature genes tend to occupy higher
#' expression ranks, whereas lower scores indicate weaker signature activity.
#'
#' This function is implemented as an S4 generic and supports multiple input
#' formats for signature_genes, including character vectors, named lists,
#' GeneSet objects, and GeneSetCollection objects.
#'
#' @param sparoranks A numeric matrix of gene ranks named sparoranks returned by
#' \code{\link{get_sparoranks}}. Rows correspond to genes and columns
#' correspond to samples, cells, or spatial domains.
#'
#' @param rank_caps A named numeric vector containing the rank cap associated
#' with each column of sparoranks. Typically obtained from the
#' rank_caps component returned by \code{\link{get_sparoranks}}.
#'
#' When supplying custom rank caps, names should match the column names of
#' sparoranks.
#'
#' @param signature_genes Gene signature(s) to score.
#'
#' Supported inputs include:
#' \itemize{
#' \item A character vector representing a single gene signature.
#' \item A named list of character vectors representing multiple gene
#' signatures.
#' \item A GeneSet object.
#' \item A GeneSetCollection object.
#' }
#'
#' Gene identifiers must use the same naming convention as the row names of
#' sparoranks.
#'
#' @param handle_missing_genes Character string specifying how signature genes
#' absent from sparoranks should be handled.
#'
#' Supported options are:
#' \describe{
#' \item{"skip"}{
#' Exclude missing genes from score calculation (default).
#' }
#'
#' \item{"impute"}{
#' Include missing genes by assigning them the capped rank value.
#' }
#' }
#'
#' @return
#' A numeric matrix of SPAROscores.
#'
#' For a single signature, the returned matrix contains one column named
#' "SPAROscore" and one row per sample, cell, or spatial domain.
#'
#' For multiple signatures, rows correspond to samples, cells, or spatial
#' domains and columns correspond to signatures.
#'
#' @details
#' The supplied signature genes are first matched against the genes available
#' in sparoranks. Missing genes are reported and handled according to
#' handle_missing_genes.
#'
#' For each sample, cell, or spatial domain, SPAROscores are computed using
#' \code{\link{compute_sparoscores}}, which evaluates the normalized Spearman
#' footrule distance between observed signature gene ranks and the
#' column-specific rank cap.
#'
#' Rank caps typically correspond to the rank of the geometric mean expression
#' value estimated by \code{\link{get_sparoranks}}, although custom rank caps
#' may also be supplied.
#'
#' @export
#'
#' @examples
#' # Compute ranks and rank caps
#' rank_results <- get_sparoranks(counts_data)
#'
#' # Score a single gene signature
#' scores <- get_sparoscores(
#' sparoranks = rank_results$sparoranks,
#' rank_caps = rank_results$rank_caps,
#' signature_genes = c("geneA", "geneC")
#' )
#'
#' # Score multiple signatures
#' scores <- get_sparoscores(
#' sparoranks = rank_results$sparoranks,
#' rank_caps = rank_results$rank_caps,
#' signature_genes = list(
#' sigA = c("geneA", "geneC"),
#' sigB = c("geneB", "geneD")
#' )
#' )
#'
#'
# set the generic for get_sparoscores() methods
setGeneric("get_sparoscores",
           function(sparoranks,
                    rank_caps,
                    signature_genes,
                    handle_missing_genes = "skip")
               standardGeneric("get_sparoscores"))




# set the method for get_sparoscores() where signature_genes is a
# character vector
setMethod("get_sparoscores",
          signature('ANY','ANY', 'character', "ANY"),
          function(sparoranks,
                   rank_caps,
                   signature_genes,
                   handle_missing_genes = "skip"){

              #call the helper function
              sparoscores <- compute_sparoscores(
                  sparoranks,
                  rank_caps,
                  signature_genes,
                  handle_missing_genes = handle_missing_genes)

              # add columnnames
              sparoscores <- as.matrix(sparoscores)
              colnames(sparoscores) <- "SPAROscore"

              return(sparoscores)
          }
)


# set the method for get_sparoscores() where signature_genes is a
# named list
setMethod("get_sparoscores",
          signature('ANY','ANY', 'list', "ANY"),
          function(sparoranks,
                   rank_caps,
                   signature_genes,
                   handle_missing_genes = "skip"){

              #call the helper function with vapply
              sparoscores <- vapply(X = signature_genes,
                                   FUN = function(x){
                                              compute_sparoscores(
                                              sparoranks,
                                              rank_caps,
                                              x,
                                              handle_missing_genes =
                                                  handle_missing_genes)
                                          },
                                   FUN.VALUE = numeric(ncol(sparoranks)))
              return(sparoscores)
          }
)



# set the method for get_sparoscores() where signature_genes is a
# GeneSet S4 class
setMethod("get_sparoscores",
          signature('ANY','ANY', 'GeneSet', "ANY"),
          function(sparoranks,
                   rank_caps,
                   signature_genes,
                   handle_missing_genes = "skip"){

              #call the helper function
              sparoscores <- compute_sparoscores(
                  sparoranks,
                  rank_caps,
                  GSEABase::geneIds(signature_genes),
                  handle_missing_genes = handle_missing_genes)

              # add columnnames after transposing
              sparoscores <- as.matrix(sparoscores)
              colnames(sparoscores) <- "SPAROscores"
              return(sparoscores)
          }
)


# set the method for get_sparoscores() where signature_genes is a
# GeneSetCollection S4 class
setMethod("get_sparoscores",
          signature('ANY','ANY', 'GeneSetCollection', "ANY"),
          function(sparoranks,
                   rank_caps,
                   signature_genes,
                   handle_missing_genes = "skip"){

              #call the helper function with vapp
              sparoscores <- vapply(X = GSEABase::geneIds(signature_genes),
                                    FUN = function(x){
                                        compute_sparoscores(
                                            sparoranks,
                                            rank_caps,
                                            x,
                                            handle_missing_genes =
                                                handle_missing_genes)
                                    },
                                    FUN.VALUE = numeric(ncol(sparoranks)))
              colnames(sparoscores) <- names(signature_genes)
              return(sparoscores)
          }
)
