#' Compute SPAROscores from pre-computed gene ranks. \cr
#' \emph{get_sparoscores()} calculates gene signature scores for each sample,
#' cell,or spatial domain using the rank matrix and rank caps generated by
#' \emph{get_sparoranks()}. \cr
#' Scores are based on the Spearman Footrule distance between the observed ranks
#'  of signature genes and their corresponding rank caps. \cr
#' By default, rank caps correspond to the rank of the geometric mean
#' expression estimated by \emph{get_sparoranks()}, although custom rank caps
#' can also be supplied.
#'
#' @param sparoranks A numeric matrix of gene ranks returned as the
#' \emph{sparoranks} component of \emph{get_sparoranks()}. Rows correspond to
#' genes and columns correspond to samples, cells, or spatial domains.
#'
#' @param rank_caps A named numeric vector of rank caps, typically the
#' \emph{rank_caps} component returned by \emph{get_sparoranks()}. Each value is used
#' as the rank cap for the corresponding column in sparoranks. When
#' supplying custom rank caps, names must match the column names of
#' sparoranks.
#'
#' @param signature_genes Gene signature(s) to score.
#'\cr
#' For a single signature: provide either a character vector of gene identifiers
#' or a GeneSet object.
#'\cr
#' For multiple signatures: provide either z named list of character vectors,
#' (where each list element contains gene
#' identifiers and the element name specifies the signature name) or
#' a GeneSetCollection object. \cr
#' Gene identifiers must use the same naming convention as the row names of
#' \emph{sparoranks}.
#'
#'
#' @param handle_missing_genes Character string specifying how signature genes
#' that are absent from the input data should be handled.
#' \describe{
#' \item{skip}{Remove missing genes from the score calculation
#' (default).}
#' \item{impute}{Treat missing genes as having zero expression and
#' include them in the analysis.}
#' }
#'
#' @returns
#' A numeric matrix with SPAROscores for each gene signature in columns and
#' samples, cells, or domains in rows
#'
#'
#' @details
#' SPAROscores quantify the deviation between observed signature gene ranks
#' and the estimated scenario of signature inactivity defined by the rank caps.
#' Lower scores indicate that signature genes are not very active and higher
#' scores indiacte high signature activity.
#'
#' @export
#'
#'
#' @examples
#' # Compute ranks and rank caps
#' sparorank_output <- get_sparoranks(counts_data)
#'
#' # Score a single gene signature
#' sparoscores <- get_sparoscores(
#' sparoranks = sparorank_output$sparoranks,
#' rank_caps = sparorank_output$rank_caps,
#' signature_genes = c("geneA", "geneC")
#' )
#'
#' # Score multiple gene signatures
#' sparoscores <- get_sparoscores(
#' sparoranks = sparorank_output$sparoranks,
#' rank_caps = sparorank_output$rank_caps,
#' signature_genes = list(
#' sigA = c("geneA", "geneC"),
#' sigB = c("geneB", "geneD")
#' )
#' )


# set the generic for get_sparoscores() methods
setGeneric("get_sparoscores",
           function(sparoranks,
                    rank_caps,
                    signature_genes,
                    handle_missing_genes = "skip")
               standardGeneric("get_sparoscores"))




# set the method for get_sparoscores() where signature_genes is a
# character vector
setMethod("get_sparoscores",
          signature('ANY','ANY', 'character', "ANY"),
          function(sparoranks,
                   rank_caps,
                   signature_genes,
                   handle_missing_genes = "skip"){

              #call the helper function
              sparoscores <- compute_sparoscores(
                  sparoranks,
                  rank_caps,
                  signature_genes,
                  handle_missing_genes = "skip")

              # add columnnames
              sparoscores <- as.matrix(sparoscores)
              colnames(sparoscores) <- "SPAROscore"

              return(sparoscores)
          }
)


# set the method for get_sparoscores() where signature_genes is a
# named list
setMethod("get_sparoscores",
          signature('ANY','ANY', 'list', "ANY"),
          function(sparoranks,
                   rank_caps,
                   signature_genes,
                   handle_missing_genes = "skip"){

              #call the helper function with vapply
              sparoscores <- vapply(X = signature_genes,
                                   FUN = function(x){
                                              compute_sparoscores(
                                              sparoranks,
                                              rank_caps,
                                              x,
                                              handle_missing_genes = "skip")
                                          },
                                   FUN.VALUE = numeric(ncol(sparoranks)))
              return(sparoscores)
          }
)



# set the method for get_sparoscores() where signature_genes is a
# GeneSet S4 class
setMethod("get_sparoscores",
          signature('ANY','ANY', 'GeneSet', "ANY"),
          function(sparoranks,
                   rank_caps,
                   signature_genes,
                   handle_missing_genes = "skip"){

              #call the helper function
              sparoscores <- compute_sparoscores(
                  sparoranks,
                  rank_caps,
                  GSEABase::geneIds(signature_genes),
                  handle_missing_genes = "skip")
              colnames(sparoscores) <- names(signature_genes)

              # add columnnames after transposing
              sparoscores <- as.matrix(sparoscores)
              colnames(sparoscores) <- "SPAROscores"
              return(sparoscores)
          }
)


# set the method for get_sparoscores() where signature_genes is a
# GeneSetCollection S4 class
setMethod("get_sparoscores",
          signature('ANY','ANY', 'GeneSetCollection', "ANY"),
          function(sparoranks,
                   rank_caps,
                   signature_genes,
                   handle_missing_genes = "skip"){

              #call the helper function with vapp
              sparoscores <- vapply(X = GSEABase::geneIds(signature_genes),
                                    FUN = function(x){
                                        compute_sparoscores(
                                            sparoranks,
                                            rank_caps,
                                            x,
                                            handle_missing_genes = "skip")
                                    },
                                    FUN.VALUE = numeric(ncol(sparoranks)))
              colnames(sparoscores) <- names(signature_genes)
              return(sparoscores)
          }
)
